.TH tutka 1 "December 12 2018"
.SH NAME
tutka \- tracker style MIDI sequencer
.SH SYNOPSIS
.B tutka
.RI "files" ...
.SH DESCRIPTION
This manual page documents briefly the
.B tutka
command.
.PP
\fBtutka\fP is a tracker style MIDI sequencer similar to SoundTracker,
 or Protracker except that it does not support samples and is meant
 for MIDI use only.
.SH OPTIONS
No options are supported.
.SH SEE ALSO
.BR protracker (1),
.BR traverso (1),
.BR qtractor (1).
.br
