#!/bin/bash

REPO_LIST="https://github.com/Abjad/abjad
https://github.com/jpcima/ADLplug.git
https://git.laborejo.org/lss/agordejo.git
https://github.com/sourcefabric/airtime.git
https://github.com/airwindows/airwindows
https://github.com/karldd/Alchemy
https://github.com/bubbapizza/alsacap
https://github.com/blablack/ams-lv2.git
https://github.com/amsynth/amsynth.git
https://github.com/pjz/amuc.git
https://github.com/chronopoulos/annulus
git://git.ardour.org/ardour/ardour.git
https://git.laborejo.org/lss/argodejo.git
https://github.com/aubio/aubio.git
https://github.com/jeremysalwen/Aubio-LV2-Plugins.git
https://github.com/audacity/audacity.git
https://gitlab.com/ayrsd/audiostellar
https://github.com/Audiveris/audiveris.git
https://github.com/x42/avldrums.lv2
https://github.com/madskjeldgaard/awesome-supercollider
https://github.com/axoloti/axoloti.git
git://git.sv.gnu.org/ll-plugins/azr3-jack.git
https://git.code.sf.net/p/backupband/code
https://github.com/rerrahkr/BambooTracker.git
https://github.com/jpcima/Bass21
https://github.com/tim-janik/beast.git
https://github.com/DanielRudrich/BeatAligningGuitarLooper
https://github.com/mortuosplango/beenoir.git
https://github.com/cappelnord/BenoitLib
https://github.com/awwbees/BespokeSynth
https://github.com/jperler/bezie.git
https://gitlab.domainepublic.net/bipscript/bipscript
https://github.com/rafaelmardojai/blanket
https://github.com/sjaehn/Bsequencer
https://github.com/sjaehn/BShapr.git
https://github.com/sjaehn/BSpacr
https://github.com/Buzztrax/buzztrax
https://github.com/rorywalsh/cabbage
https://github.com/falkTX/Cadence.git
git@github.com:calf-studio-gear/calf.git
https://github.com/pierreguillot/Camomile
https://github.com/DISTRHO/Cardinal
https://github.com/falkTX/Carla.git
https://github.com/belangeo/cecilia5.git
https://github.com/benkuper/Chataigne
https://github.com/Chowdhury-DSP/ChowMatrix
https://github.com/cinder/Cinder
https://github.com/danmar/cppcheck
https://github.com/RomanKubiak/ctrlr.git
https://github.com/curv3d/curv.git
https://github.com/rafael2k/darkice.git
https://github.com/phusion/debian-packaging-for-the-modern-developer
https://github.com/sonejostudios/DeLooper
git://git.savannah.gnu.org/denemo.git
https://github.com/asb2m10/dexed
http://git.drumgizmo.org/dgedit.git
https://github.com/oswald2/DGPatchMaker
https://github.com/LouisGorenfeld/DigitsVst
https://git.savannah.nongnu.org/git/dino.git
https://github.com/DISTRHO/DISTRHO-Ports.git
https://github.com/DISTRHO/DISTRHO-Ports-Extra.git
https://git.code.sf.net/p/djv/git
https://github.com/DISTRHO/DPF
https://github.com/DISTRHO/plugin-examples.git
https://github.com/DISTRHO/gl-examples.git
https://github.com/AuburnSounds/Dplug
https://github.com/michaelwillis/dragonfly-reverb.git
https://github.com/DynamoRIO/drmemory.git
https://github.com/falkTX/drmr.git
http://git.drumgizmo.org/drumgizmo.git
https://github.com/rncbc/drumkv1
https://github.com/falkTX/dssi-vst
https://github.com/Sciss/Eisenkraut
https://github.com/kushview/Element
git@github.com:bill-brown/emap.git
https://github.com/EmissionControl2/EmissionControl2
https://github.com/jpcima/ensemble-chorus.git
https://github.com/digego/extempore.git
https://github.com/grame-cncm/faust
git://git.code.sf.net/p/faudiostream/faustlive
https://bitbucket.org/agraef/faust-lv2/src
https://github.com/grame-cncm/faustworks.git
https://src.fedoraproject.org/rpms/kernel.git
https://pagure.io/fedora-kickstarts.git
https://pagure.io/fedora-misc-package-utilities.git
https://github.com/x42/fil4.lv2
https://github.com/eclab/flow
https://github.com/brummer10/Fluida.lv2
https://github.com/FluidSynth/fluidsynth
https://github.com/linuxmao-org/fogpad-port
https://github.com/dyne/FreeJ
https://github.com/free-wheeling/freewheeling
https://github.com/essej/freqtweak
https://github.com/linuxmao-org/Frontieres.git
https://github.com/8bitbubsy/ft2-clone
https://github.com/bigfug/Fugio.git
https://github.com/generative-design/Code-Package-p5.js.git
https://gitlab.com/genhydro/genhydro
https://gitlab.com/NaN9/geohead
https://gitlab.com/geontime/geonkick
https://git.savannah.nongnu.org/git/getfem.git
https://github.com/monocasual/giada
https://github.com/wacossusca34/glava.git
https://git.savannah.gnu.org/git/solfege.git
git://git.code.sf.net/p/guitarix/git
https://github.com/snappy46/GuitarixDroid.git
https://github.com/snappy46/GuitarixMidiController.git
https://git.code.sf.net/p/guvcview/git-master
https://github.com/brummer10/GxPlugins.lv2.git
https://github.com/brummer10/GxReverseDelay.lv2
https://github.com/brummer10/gxtuner.git
https://github.com/x42/harvid.git
https://github.com/helio-fm/helio-workstation
https://github.com/mtytel/helm.git
https://github.com/christophhart/HISE.git
https://github.com/pete-gordon/hivelytracker
https://github.com/Wasted-Audio/hvcc
https://github.com/jpcima/HybridReverb2
https://github.com/hydrogen-music/hydrogen
https://github.com/TuriSc/hydrogen2drumkv1.py/
https://github.com/tresf/hydrogen-drumkits
https://github.com/iannix/IanniX.git
https://github.com/alexadam/img-encode.git
https://github.com/benthevining/imogen
https://github.com/Impro-Visor/Impro-Visor.git
https://github.com/rumblesan/improviz
git://gabe.is-a-geek.org/git/inconcert.git
https://github.com/ssj71/infamousPlugins.git
git://git.code.sf.net/p/isse/code
https://github.com/jackaudio/jack1
https://github.com/jackaudio/jack2
git@github.com:ycollet/jackmidilogger.git
https://github.com/jack-mixer/jack_mixer
https://github.com/spark404/jalmus.git
https://github.com/brummer10/jalv_select
git://git.code.sf.net/p/jamin/code
https://github.com/elieserdejesus/JamTaba/
https://github.com/corrados/jamulus
https://github.com/jjazzboss/JJazzLab-X
https://github.com/harryhaaren/jm2cv.git
https://github.com/Joeboy/joeboy-lv2-plugins.git
https://github.com/json-c/json-c.git
https://github.com/juce-framework/JUCE
https://github.com/kunitoki/juced.git
git://repo.or.cz/juce-lv2.git
https://github.com/olegkapitonov/Kapitonov-Plugins-Pack
https://github.com/oli-kester/kepler34.git
https://github.com/dsacre/klick.git
https://github.com/jatinchowdhury18/KlonCentaur
https://github.com/kometbomb/klystrack.git
https://github.com/mzuther/K-Meter.git
https://github.com/noedigcode/konfyt
git://git.code.sf.net/p/kwave/code
https://invent.kde.org/graphics/kxstitch.git/
https://gitlab.com/lebiniou/lebiniou.git
https://gitlab.com/lebiniou/lebiniou-data
https://github.com/lenmus/lenmus.git
git://liblo.git.sourceforge.net/gitroot/liblo/liblo
https://gitlab.com/LibreArp/LibreArp
https://github.com/stump/libsmf.git
https://github.com/memononen/libtess2
https://github.com/FrancescoCeruti/linux-show-player.git
https://github.com/kenrestivo/Linux-synth-patches.git
https://github.com/livecd-tools/livecd-tools.git
https://github.com/salsaman/LiVES.git
git://git.sv.gnu.org/ll-plugins.git
https://github.com/LMMS/lmms.git
https://github.com/LMMS/assets.git
https://github.com/pgiblock/lmms-lv2.git
https://github.com/PaulBatchelor/lmms-reverbsc.git
https://github.com/PaulBatchelor/LMMS-Signal.git
https://github.com/PaulBatchelor/LMMS-Sporth.git
https://github.com/muse-sequencer/muse.git
https://github.com/neilcosgrove/LNX_Studio.git
https://github.com/lenmus/lomse.git
https://github.com/radarsat1/LoopDub.git
https://github.com/bill-auger/loopidity
https://github.com/stevie67/loopor
https://gitlab.com/sonusdept/loopus
https://github.com/weldr/lorax.git
https://github.com/sadko4u/lsp-plugins
https://github.com/LuaAV/LuaAV.git
https://github.com/lighttroupe/luz.git
https://github.com/lv2/lv2
https://github.com/jeremysalwen/lv2file
https://gitlab.com/drobilla/lv2lint
http://git.elephly.net/software/lv2-mdametapiano.git
https://github.com/lvtk/lvtk.git
git://git.lyx.org/lyx
https://github.com/brummer10/Mamba
https://github.com/kmatheussen/mammut
https://github.com/mandelbulb-4d/mandelbulb-4d
https://github.com/buddhi1980/mandelbulber2
https://github.com/mapmapteam/mapmap.git
https://github.com/RPTools/maptool
https://github.com/thargor6/mb3d
https://git.open-music-kontrollers.ch/lv2/mephisto.lv2
https://github.com/dblanchemain/metaSurface
https://github.com/supergilbert/midilooper.git
https://github.com/cbdevnet/midimonster
https://github.com/jberg/milkdrop-editor-electron
https://github.com/milkytracker/MilkyTracker.git
https://github.com/jeremysalwen/Minicomputer-LV2.git
https://github.com/mixxxdj/mixxx.git
https://github.com/muammar/mkchromecast
https://github.com/d3cod3/Mosaic
https://github.com/stavrosdidakis/Motion-Tracking
https://github.com/PiOverFour/MPK-M2-editor
https://github.com/musescore/MuseScore.git
https://github.com/munt/munt.git
git://git.code.sf.net/p/mv-6pm/code
git@github.com:linuxmao-org/Mx44.git
https://github.com/napframework/nap
https://github.com/MrKepzie/Natron.git
https://github.com/linuxaudio/new-session-manager
https://github.com/rghvdberg/ninjas2
https://github.com/tialaramex/njl-plugins.git
https://github.com/nodebox/nodebox
https://github.com/nodebox/nodebox-pyobjc
https://github.com/lucianodato/noise-repellent
git@github.com:ycollet/non.git
git://git.tuxfamily.org/gitroot/non/non.git
https://github.com/falkTX/non
git@github.com:ycollet/ntk.git
git://git.tuxfamily.org/gitroot/non/fltk.git
https://github.com/reales/OB-Xd
https://github.com/TheWaveWarden/odin2
https://github.com/turcofran/omfootctrl
https://github.com/Music-and-Culture-Technology-Lab/omnizart
https://github.com/OpenBoard-org/OpenBoard
https://github.com/openframeworks/openFrameworks.git
https://github.com/jean-emmanuel/open-stage-control
https://github.com/hundredrabbits/Orca
https://git.sr.ht/~rabbits/orca
https://github.com/RichardHladik/outotune
https://github.com/oxesoft/oxefmsynth.git
https://github.com/rncbc/padthv1
https://bitbucket.org/xenakios/paulstretchplugin.git
git://git.code.sf.net/p/pure-data/pd-anywhere
git://git.code.sf.net/p/pure-data/pd-extended
https://github.com/pd-l2ork/pd-l2ork
https://github.com/logsol/pd-pulp
https://github.com/progwolff/performer
https://github.com/williamweston/phasex.git
https://github.com/foolswood/Physyn
https://github.com/captnfab/PianoBooster.git
https://github.com/yoyz/audio.git
https://gitlab.freedesktop.org/pipewire/pipewire
https://gitlab.com/davethecomposer/platonic-music-engine/
https://github.com/jwagner/playitslowly.git
https://github.com/danfrz/PLEBTracker
https://github.com/Houston4444/plujain-ramp
https://github.com/polyeffects/PolyLV2
https://github.com/davy7125/polyphone.git
https://git.assembla.com/portaudio.git
https://salsa.debian.org/multimedia-team/portsmf
https://github.com/praxis-live/praxis.git
https://github.com/praxis-live/examples
https://github.com/praxis-live/praxis-live.git
https://github.com/projectM-visualizer/projectm
https://github.com/DISTRHO/ProM
https://github.com/echolevel/protracker
https://github.com/falkTX/protrekkr.git
https://github.com/hitchhikr/protrekkr
https://git.code.sf.net/p/industrializer/code
https://github.com/8bitbubsy/pt2-clone
git://anongit.freedesktop.org/pulseaudio/pulseaudio
git://git.code.sf.net/p/pure-data/pure-data
https://github.com/agraef/purr-data
https://github.com/milanboers/pytune.git
https://github.com/magnusjonsson/qin.git
https://github.com/rncbc/qjackctl
https://github.com/rncbc/qmidinet
https://github.com/rncbc/qsynth
git://git.code.sf.net/p/qtgain/code
https://github.com/rncbc/qtractor
https://github.com/zbanks/radiance
https://github.com/kmatheussen/radium.git
git://git.code.sf.net/p/rakarrack/git
https://github.com/Stazed/rakarrack-plus
https://github.com/Houston4444/RaySession
https://github.com/raboof/realtimeconfigquickscan.git
https://github.com/gbevin/ReceiveMIDI
https://github.com/ElvishArtisan/rivendell.git
https://github.com/ssj71/rkrlv2.git
https://github.com/njh/rotter.git
https://codeberg.org/rtcqs/rtcqs
https://github.com/rncbc/rtirq.git
git://git.kernel.org/pub/scm/linux/kernel/git/clrkwllms/rt-tests.git
https://github.com/ayyi/samplecat
https://gitlab.com/samplehive/sample-hive.git
https://github.com/rncbc/samplv1
https://github.com/supercollider/sc3-plugins.git
https://github.com/schismtracker/schismtracker
https://github.com/brummer10/screcord.lv2
https://github.com/gbevin/SendMIDI
https://github.com/Stazed/seq42.git
https://github.com/ahlstromcj/sequencer64.git
https://github.com/pantherb/setBfree.git
https://github.com/wschweer/sftools.git
https://github.com/dfranx/SHADERed
https://github.com/surge-synthesizer/shortcircuit-xt
https://github.com/evandelisle/showq.git
https://github.com/rock-hopper/shuriken.git
https://github.com/paulpacifico/shutter-encoder
https://github.com/njh/silentjack.git
https://github.com/GuitarML/SmartGuitarAmp
https://github.com/50m30n3/SO-666.git
https://github.com/samaaron/sonic-pi.git
https://github.com/markandrus/Sonify
https://github.com/essej/sonobus
https://github.com/essej/sooperlooper.git
https://github.com/jeremysalwen/So-synth-LV2.git
https://github.com/soul-lang/SOUL
https://github.com/belangeo/soundgrain.git
https://github.com/SoundScapeRenderer/ssr
https://github.com/leomccormack/SPARTA.git
https://github.com/leomccormack/Spatial_Audio_Framework
https://github.com/swesterfeld/spectmorph
https://gitlab.com/sat-metalab/splash
https://github.com/deezer/spleeter
https://github.com/stargateaudio/stargate
https://github.com/surge-synthesizer/stochas
https://github.com/smbolton/stretchplayer.git
https://invent.kde.org/multimedia/subtitlecomposer.git
https://github.com/sonejostudios/SuperBeatRepeater
git@github.com:Vampouille/superboucle.git
https://github.com/supercollider/supercollider.git
https://github.com/augustofilocamo/superOrgan
https://github.com/surge-synthesizer/surge
git://git.code.sf.net/p/swami/code
https://github.com/swh/lv2.git
https://github.com/surfacepatterns/synthclone
https://github.com/rncbc/synthv1
https://github.com/kokizzu/talentledhack.git
https://github.com/HoerTech-gGmbH/tascar
https://github.com/axkg/terminatorX
https://github.com/x42/testsignal.lv2
https://github.com/kellydimmick/TheEyeHarp
https://github.com/crabacus/the-open-source-drumkit.git
https://git.code.sf.net/p/thmad/code
https://github.com/sadko4u/timbre-mill
https://github.com/swh/timemachine.git
https://git.code.sf.net/p/timewave-synthesizer/code
https://github.com/mzuther/traKmeter.git
https://git.savannah.gnu.org/git/traverso.git
https://github.com/dsheeler/tremelo.lv2
https://github.com/paynebc/tunefish.git
https://github.com/surge-synthesizer/tuning-workbench-synth
https://github.com/DCubix/Twist
https://github.com/txmod/TXModular.git
https://github.com/coderofsalvation/usm
https://gitlab.com/smart-pattern/valentina.git
https://github.com/c0ntrol/veejay.git
https://github.com/rdybka/vht
https://github.com/mtytel/vital
https://github.com/kragen/viznut-music
https://github.com/linuxmao-org/VL1-emulator.git
https://github.com/sgossner/VSCO-2-CE
https://github.com/steinbergmedia/vst3sdk.git
https://github.com/reuk/wayverb
git://source.winehq.org/git/wine.git
https://github.com/pdesaulniers/wolf-shaper.git
https://github.com/brummer10/XDarkTerror.lv2
https://github.com/x42/xjadeo.git
https://github.com/brummer10/XTinyTerror.lv2
https://github.com/brummer10/XUiDesigner
http://xwax.org/devel/xwax.git
https://github.com/robbert-vdh/yabridge
git://git.code.sf.net/p/yoshimi/code
https://github.com/YruamaLairba/yru-simple-LV2-C
https://github.com/zamaudio/zam-plugins.git
https://github.com/chronopoulos/ziggurat
https://github.com/zrythm/ZPlugins
https://git.zrythm.org/zrythm/zrythm
https://git.sr.ht/~alextee/zrythm-libcyaml
https://git.zrythm.org/zrythm/zrythm-media/
https://github.com/zynaddsubfx/zynaddsubfx
https://github.com/belangeo/zyne.git
https://github.com/zynaddsubfx/zyn-fusion-build
https://github.com/zynthian/zynthian-data.git
https://github.com/reduz/zytrax.git"

if [ -f git_tqgs_new.txt ];
then
    mv git_tqgs_new.txt git_tqgs_old.txt
fi

for File in $REPO_LIST
do
    LINE="$File `git ls-remote --tags $File 2>&1 | grep -v redirect | tail --lines=1`"
    TAGS=`echo "$LINE" | grep "refs/tags"`
    if [ ! -z "$TAGS" ];
    then
	echo "$LINE"
	echo "$LINE" >> git_tqgs_new.txt
    fi
done

if [ -f git_tqgs_old.txt ];
then
    diff git_tqgs_new.txt git_tqgs_old.txt
fi
