#!/bin/bash
set -e

OUTDIR="/run/systemd/user/pipewire.service.d"

mkdir -p "$OUTDIR"

# Eligibility checks
/usr/libexec/audio-topology-profile/detect.sh || exit 0

# Build CPU profile
AUDIO_CPUS=$(
    /usr/libexec/audio-topology-profile/build-profile.sh
)

[ -z "$AUDIO_CPUS" ] && exit 0

cat > "$OUTDIR/10-audio-topology.conf" <<EOF
[Service]
CPUAffinity=$AUDIO_CPUS
EOF
